/**
 * Hajj Guide — Cloudflare Worker
 *
 * Routes:
 *   GET  /js/config.js   — dynamically generated, inlines the Google Maps API key
 *   POST /api/like       — increments the global "like" counter in KV
 *   GET  /api/like       — returns the current count
 *   POST /api/share      — increments the global "share" counter in KV
 *   GET  /api/share      — returns the current count
 *   *                    — falls through to env.ASSETS.fetch (static files)
 *
 * Bindings (set via wrangler.jsonc and the Cloudflare dashboard):
 *   env.ASSETS              — static asset binding (already present)
 *   env.GOOGLE_MAPS_API_KEY — secret, set via `wrangler secret put`
 *   env.LIKES               — KV namespace binding (added in Cloudflare dashboard)
 */

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': 'https://hajjguide.net',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Access-Control-Max-Age': '86400',
};

function jsonResponse(body, status = 200, extraHeaders = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      ...CORS_HEADERS,
      ...extraHeaders,
    },
  });
}

async function handleConfig(env) {
  const apiKey = (env && env.GOOGLE_MAPS_API_KEY) || '';
  const config = {
    googleMapsApiKey: apiKey,
    enablePlacesAutocomplete: !!apiKey,
    analyticsUrl: null,
  };
  const body = `/* Generated by Cloudflare Worker — do not edit. */
window.APP_CONFIG = ${JSON.stringify(config, null, 2)};
`;
  return new Response(body, {
    status: 200,
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
      'X-Content-Type-Options': 'nosniff',
    },
  });
}

/**
 * v2.3 — Generic KV counter handler. Used by /api/like and /api/share.
 * The same KV namespace (LIKES) stores both, under different keys.
 */
async function handleCounter(request, env, kvKey) {
  if (request.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: CORS_HEADERS });
  }
  if (!env.LIKES) {
    if (request.method === 'GET') return jsonResponse({ count: 0 });
    if (request.method === 'POST') return jsonResponse({ ok: true, count: 0 });
    return jsonResponse({ error: 'Method not allowed' }, 405);
  }

  if (request.method === 'GET') {
    const raw = await env.LIKES.get(kvKey);
    const count = parseInt(raw || '0', 10) || 0;
    return jsonResponse({ count }, 200, {
      'Cache-Control': 'public, max-age=15',
    });
  }

  if (request.method === 'POST') {
    const raw = await env.LIKES.get(kvKey);
    const current = parseInt(raw || '0', 10) || 0;
    const next = current + 1;
    await env.LIKES.put(kvKey, String(next));
    return jsonResponse({ ok: true, count: next });
  }

  return jsonResponse({ error: 'Method not allowed' }, 405);
}

// Backwards-compat thin wrappers
async function handleLike(request, env)  { return handleCounter(request, env, 'total'); }
async function handleShare(request, env) { return handleCounter(request, env, 'share-total'); }

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // v3.1 — Canonical host enforcement.
    // hajjguide.net is the canonical host. www.hajjguide.net redirects with 301
    // so search engines consolidate signals on a single canonical URL.
    // The redirect preserves the path, query string and fragment.
    if (url.hostname === 'www.hajjguide.net') {
      const canonical = new URL(request.url);
      canonical.hostname = 'hajjguide.net';
      return Response.redirect(canonical.toString(), 301);
    }

    if (url.pathname === '/js/config.js') return handleConfig(env);
    if (url.pathname === '/api/like')     return handleLike(request, env);
    if (url.pathname === '/api/share')    return handleShare(request, env);

    // v3.6 — Pass to static asset handler, then add cache-control headers
    // appropriate for the file type so updates propagate to users promptly.
    const assetResponse = await env.ASSETS.fetch(request);

    // Don't add headers to redirects or error responses
    if (!assetResponse.ok && assetResponse.status !== 304) {
      return assetResponse;
    }

    const cacheControl = pickCacheControl(url.pathname);
    if (!cacheControl) return assetResponse;

    // Clone the response so we can modify headers (Response is immutable by default)
    const headers = new Headers(assetResponse.headers);
    headers.set('Cache-Control', cacheControl);
    return new Response(assetResponse.body, {
      status: assetResponse.status,
      statusText: assetResponse.statusText,
      headers,
    });
  },
};

/**
 * v3.6 — Pick the right Cache-Control header for a given asset.
 *
 * - `sw.js`           : no-cache. The browser revalidates on every load
 *                       so SW updates are detected immediately.
 * - HTML              : no-cache. Always send a conditional request so
 *                       the user gets the latest page shell. The SW also
 *                       does network-first for HTML, so this aligns.
 * - JSON data files   : short max-age (5 min) + must-revalidate. Updates
 *                       to duas/rulings propagate within a few minutes,
 *                       even past the SW's network-first behaviour.
 * - JS/CSS/images     : 5-min cache for repeat-visit speed; the SW handles
 *                       offline access. When code changes, the SW's
 *                       cache-bump (BUILD_VERSION) forces re-download.
 * - Other (icons, manifest): same 5-min default.
 */
function pickCacheControl(pathname) {
  // Service worker file — must always be revalidated
  if (pathname === '/js/sw.js') {
    return 'no-cache, no-store, must-revalidate';
  }
  // HTML files — always revalidate so updated wrappers reach users
  if (pathname.endsWith('.html') || pathname === '/' || pathname === '') {
    return 'no-cache, must-revalidate';
  }
  // JSON data — short cache + revalidate
  if (pathname.endsWith('.json')) {
    return 'public, max-age=300, must-revalidate';
  }
  // JS / CSS / images — short browser cache; the service worker is the
  // primary cache layer and it's invalidated on each release.
  if (/\.(js|css|png|jpg|jpeg|webp|svg|ico|woff2?)$/i.test(pathname)) {
    return 'public, max-age=300';
  }
  return null; // no override — let Cloudflare's default apply
}

