/**
 * Hajj Guide — Cloudflare Worker
 *
 * Most requests are static assets (HTML, CSS, JS, images, JSON) and pass
 * straight through to env.ASSETS. The single dynamic route is /js/config.js,
 * which is generated on the fly using the GOOGLE_MAPS_API_KEY secret.
 *
 * The secret is set in:
 *   Cloudflare Dashboard → Workers & Pages → hajj-guide → Settings →
 *   Variables and Secrets → Add → Type: Secret →
 *   Name: GOOGLE_MAPS_API_KEY → Value: <your real key>
 */

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Dynamic config endpoint — serves window.APP_CONFIG with the API key

    console.log('env keys:', env ? Object.keys(env) : 'env is null');
    console.log('GOOGLE_MAPS_API_KEY type:', typeof env?.GOOGLE_MAPS_API_KEY);
    console.log('GOOGLE_MAPS_API_KEY length:', env?.GOOGLE_MAPS_API_KEY?.length);

    if (url.pathname === '/js/config.js') {
      const apiKey = (env && env.GOOGLE_MAPS_API_KEY) || '';

      const config = {
        googleMapsApiKey: apiKey,
        enablePlacesAutocomplete: !!apiKey,
        analyticsUrl: null,
      };

      const body = `/* Generated by Cloudflare Worker — do not edit. */
window.APP_CONFIG = ${JSON.stringify(config, null, 2)};
`;

      return new Response(body, {
        status: 200,
        headers: {
          'Content-Type': 'application/javascript; charset=utf-8',
          'Cache-Control': 'public, max-age=3600',
          'X-Content-Type-Options': 'nosniff',
        },
      });
    }

    // Everything else → serve as static asset from the project root
    return env.ASSETS.fetch(request);
  },
};
