/**
 * Hajj Guide — Cloudflare Worker
 *
 * Routes:
 *   GET  /js/config.js   — dynamically generated, inlines the Google Maps API key
 *   POST /api/like       — increments the global "like" counter in KV
 *   GET  /api/like       — returns the current count
 *   POST /api/share      — increments the global "share" counter in KV
 *   GET  /api/share      — returns the current count
 *   *                    — falls through to env.ASSETS.fetch (static files)
 *
 * Bindings (set via wrangler.jsonc and the Cloudflare dashboard):
 *   env.ASSETS              — static asset binding (already present)
 *   env.GOOGLE_MAPS_API_KEY — secret, set via `wrangler secret put`
 *   env.LIKES               — KV namespace binding (added in Cloudflare dashboard)
 */

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': 'https://hajjguide.net',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Access-Control-Max-Age': '86400',
};

function jsonResponse(body, status = 200, extraHeaders = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      'Content-Type': 'application/json; charset=utf-8',
      ...CORS_HEADERS,
      ...extraHeaders,
    },
  });
}

async function handleConfig(env) {
  const apiKey = (env && env.GOOGLE_MAPS_API_KEY) || '';
  const config = {
    googleMapsApiKey: apiKey,
    enablePlacesAutocomplete: !!apiKey,
    analyticsUrl: null,
  };
  const body = `/* Generated by Cloudflare Worker — do not edit. */
window.APP_CONFIG = ${JSON.stringify(config, null, 2)};
`;
  return new Response(body, {
    status: 200,
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
      'X-Content-Type-Options': 'nosniff',
    },
  });
}

/**
 * v2.3 — Generic KV counter handler. Used by /api/like and /api/share.
 * The same KV namespace (LIKES) stores both, under different keys.
 */
async function handleCounter(request, env, kvKey) {
  if (request.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: CORS_HEADERS });
  }
  if (!env.LIKES) {
    if (request.method === 'GET') return jsonResponse({ count: 0 });
    if (request.method === 'POST') return jsonResponse({ ok: true, count: 0 });
    return jsonResponse({ error: 'Method not allowed' }, 405);
  }

  if (request.method === 'GET') {
    const raw = await env.LIKES.get(kvKey);
    const count = parseInt(raw || '0', 10) || 0;
    return jsonResponse({ count }, 200, {
      'Cache-Control': 'public, max-age=15',
    });
  }

  if (request.method === 'POST') {
    const raw = await env.LIKES.get(kvKey);
    const current = parseInt(raw || '0', 10) || 0;
    const next = current + 1;
    await env.LIKES.put(kvKey, String(next));
    return jsonResponse({ ok: true, count: next });
  }

  return jsonResponse({ error: 'Method not allowed' }, 405);
}

// Backwards-compat thin wrappers
async function handleLike(request, env)  { return handleCounter(request, env, 'total'); }
async function handleShare(request, env) { return handleCounter(request, env, 'share-total'); }

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    if (url.pathname === '/js/config.js') return handleConfig(env);
    if (url.pathname === '/api/like')     return handleLike(request, env);
    if (url.pathname === '/api/share')    return handleShare(request, env);

    return env.ASSETS.fetch(request);
  },
};
