/**
 * Cloudflare Pages Function — serves /js/config.js dynamically.
 *
 * The Google Maps API key lives only in the Cloudflare secret store,
 * never in the git repository. This function reads the secret at request
 * time and returns a JavaScript file the browser can execute.
 *
 * Set the secret in:
 *   Cloudflare Dashboard → your Pages project → Settings →
 *   Variables and Secrets → Add → Type: Secret →
 *   Name: GOOGLE_MAPS_API_KEY → Value: <your real key>
 *
 * Local development: this function won't run with `python3 -m http.server`.
 * Either use `npx wrangler pages dev` for full simulation, or create a
 * local `js/config.js` (gitignored) that overrides this in dev.
 */

// File is named `config.js.js` so the route matches `/js/config.js`.
// Cloudflare Pages serves this at exactly that path.

export async function onRequest(context) {
  const apiKey = (context.env && context.env.GOOGLE_MAPS_API_KEY) || '';

  // The shape of this object must match config.example.js exactly.
  const config = {
    googleMapsApiKey: apiKey,
    enablePlacesAutocomplete: !!apiKey,
    analyticsUrl: null,
  };

  // Build a JS file body that assigns to window.APP_CONFIG
  const body = `/* Generated by Cloudflare Pages Function — do not edit. */
window.APP_CONFIG = ${JSON.stringify(config, null, 2)};
`;

  return new Response(body, {
    status: 200,
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      // Cache at the edge for 1 hour. If you rotate the key, redeploy
      // (or use the Cloudflare cache purge button) to invalidate.
      'Cache-Control': 'public, max-age=3600',
      // Guard against framing
      'X-Content-Type-Options': 'nosniff',
    },
  });
}
